import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";

// metadata for the site
export const metadata: Metadata = {
  title: "Felicia Haggard Portfolio",
  description: "Generated by Next + Sanity + Tailwind CSS",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get all pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className=" bg-blue-dark responsive-page">
        {/* creating header for all pages */}
        <header className="header">
          {/* header logo that takes you to home page */}
          <Link href="/" className="responsive-logo-link">Felicia</Link>

          {/* mapping over the pages */}
          <div className="flex items-center gap-5">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="header-links">
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        
        <main className="py-20">{children}</main>
      </body>a
    </html>
  );
}
